CaleumBlog/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CaelumBlog.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Usuário")]
        public string LoginName { get; set; }

        [Required]
        [Display(Name ="Senha")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

CaleumBlog/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CaelumBlog.Models
{
    public class Post
    {
        public int ID { get; set; }

        [Required(ErrorMessage ="Campo Obrigatório")] [StringLength(50)]
        [Display(Name ="Título da obra:")]
        public string Titulo { get; set; }
        
        [Required(ErrorMessage ="Campo Obrigatório")]
        public string Resumo { get; set; }

        public string Categoria { get; set; }
        public DateTime? DataPublicacao { get; set; }
        public bool Publicado { get; set; }
    }
}

CaleumBlog/Areas/Admin/Controllers/PostController.cs
using CaelumBlog.Infra.DAO;
using CaelumBlog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CaelumBlog.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize]
    //[AllowAnonymous]
    public class PostController : Controller
    {

        private PostDAO postDAO;

        #region Construtor

        public PostController(PostDAO postDAO)
        {
            this.postDAO = postDAO;
        }

        #endregion

        #region Controller Index

        public IActionResult Index()
        {
            //ViewBag.Posts = postDAO.GetPosts();
            IList<Post> listaFilmes= postDAO.GetPosts();
            return View(listaFilmes);
        }

        #endregion

        #region Controller AdicionaPostagem
        // Controller das requisições da view AdicionaFilme
        [HttpGet]
        public IActionResult AdicionaPostagem()
        {
            var model = new Post();
            return View(model);
        }

        [HttpPost] 
        public IActionResult AdicionaPostagem(Post post)
        {
            if (ModelState.IsValid)
            {
                postDAO.Adiciona(post);
                return RedirectToAction("Index");
            }
            else
                return View("AdicionaPostagem", post);
        }
        #endregion

        #region Controller VisualizaPost

        public IActionResult VisualizaPost(int id)
        {
            Post post = postDAO.BuscaPorId(id);
            return View(post);
        }

        #endregion

        #region Action Categoria

        [HttpGet]
        public IActionResult Categoria( [Bind(Prefix = "id")] string categoria)
        {
            var listaFiltrada = postDAO.FiltraPorCategoria(categoria);
            return View("Index", model: listaFiltrada);
        }

        #endregion

        #region Action PublicaPost

        public IActionResult PublicaPost(int id)
        {
            postDAO.Publica(id);
            return RedirectToAction("Index");
        }

        #endregion

        #region Action DeletarPost

        public IActionResult DeletarPost(int id)
        {
            postDAO.Deleta(id);
            return RedirectToAction("Index");
        }

        #endregion
               
        #region Action EditaPost

        public IActionResult EditaPost(Post post)
        {
            if (ModelState.IsValid)
            {
                postDAO.SalvaAlteracoes(post);
                return RedirectToAction("Index");
            }
            else
                return View("VisualizaPost", post);
        }

        #endregion

        #region Action CategoriaAutocomplete

        [HttpPost]
        public IActionResult CategoriaAutocomplete(string termoDigitado)
        {
            var model = postDAO.ListaCategoriasQueContemTermo(termoDigitado);
            return Json(model);
        }

        #endregion

    }
}

CaleumBlog/Controllers/HomeController.cs
using CaelumBlog.Infra.DAO;
using CaelumBlog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CaelumBlog.Controllers
{
    public class HomeController : Controller
    {
        private PostDAO postDAO;

        public HomeController(PostDAO postDAO)
        {
            this.postDAO = postDAO;
        }
         
        public override void OnActionExecuted(ActionExecutedContext context)
        {
            base.OnActionExecuted(context);
            SetViewBagCategorias(); // O ViewBag será setado na execução de todas as actions
        }

        public IActionResult Index()
        {
            IList<Post> publicados = postDAO.GetPosts(somentePublicados: true);
            return View(publicados);
        }

        public IActionResult Busca(string termo)
        {
            if (termoInvalido(termo)) return RedirectToAction("Index");

            SetViewBagTermoBuscado(termo);
            IList<Post> resultadosBusca = postDAO.BuscaPeloTermo(termo);
            return View("Index", resultadosBusca);
        }


        public IActionResult Categoria([Bind(Prefix="id")]string categoria)
        {
            IList<Post> listaPostsCategoria = postDAO.FiltraPorCategoria(categoria);
            return View("Index", listaPostsCategoria);
        }


        #region Auxiliar Methods

        private void SetViewBagCategorias()
        {
            ViewBag.Categorias = postDAO.ListaCategorias();
        }

        private void SetViewBagTermoBuscado(string termo)
        {
            ViewBag.TermoBuscado = termo;
        }

        private bool termoInvalido(string termo)
        {
            return String.IsNullOrEmpty(termo);
        }
        #endregion
    }
}

CaleumBlog/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CaelumBlog.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace CaelumBlog.Controllers
{
    public class UsuarioController : Controller
    {

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Autentica(LoginViewModel model, string returnUrl = null)
        {
            ViewBag.ReturnUrl = returnUrl;

            if (ValidaLogin(model))
            {
                // Vamos gravar um cookie com dados da sessão

                // Dados para serem gravados
                var claims = new List<Claim>
                    {
                        new Claim("usuario", model.LoginName),
                        new Claim("role", "Member")
                    };

                // novo ClaimsIdentity passando a lista de claims com a qual popular o ClaimsIdentity
                var principal = new ClaimsIdentity(
                    claims: claims, 
                    authenticationType: CookieAuthenticationDefaults.AuthenticationScheme,
                    nameType: "usuario",
                    roleType: "role"
                    );

                // 
                await HttpContext.SignInAsync(new ClaimsPrincipal(principal));

                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    return Redirect("/");
                }
            }
            return RedirectToAction(Login);
        }

        private IActionResult RedirectToAction(Func<IActionResult> login)
        {
            throw new NotImplementedException();
        }

        private bool ValidaLogin(LoginViewModel model)
        {
            return true;
        }
    }
}

CaleumBlog/Areas/Admin/Views/Post/AdicionaPostagem.cshtml
@model Post
<!--Vai, manda os dados e volta para a própria view-->
<form asp-controller="Post" asp-action="AdicionaPostagem" method="post">

    @Html.EditorFor(p => p, "PostPublicacao")

    <button class="btn btn-primary" type="submit">Publicar</button>
    @*
            ANTES:
            <label>Título: <input type="text" name="titulo" required maxlength="50" value="@Model.Titulo" /></label>
        @Html.ValidationMessage("titulo")
        <label>Resumo: <input type="text" name="resumo" required value="@Model.Resumo" /></label>
        @Html.ValidationMessage("resumo")
        <label>Categoria: <input type="text" name="categoria" value="@Model.Categoria" /></label>
        @Html.ValidationMessage("categoria") *@
</form>

@section Scripts  {
    @*@Html.Partial("_Scripts"); // jeito obseleto*@
    <partial name="_Scripts" />
}

CaleumBlog/Areas/Admin/Views/Post/Index.cshtml
@model IList<Post>

@Html.ActionLink("Nova postagem", "AdicionaPostagem")

<table>
    <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Categoria</th>
        <th>Publicado</th>
    </tr>
    <tbody>
        @foreach (var postagem in Model)
        {
            <tr>
                <td>@postagem.Titulo</td>
                <td>@postagem.Resumo</td>
                <td>@postagem.Categoria</td>
                <td>
                    @if (postagem.Publicado)
                    {
                        @Html.Raw(string.Format("{0:dd/MM/yyyy}", postagem.DataPublicacao));
                    }
                    else
                    {
                        @Html.Raw("Não");
                    }
                </td>
                <td><a asp-controller="Post" asp-action="VisualizaPost" asp-route-id="@postagem.ID">Editar</a></td>
            </tr>
        }
    </tbody>

</table>

CaleumBlog/Areas/Admin/Views/Post/VisualizaPost.cshtml
@model Post

<h1>Edição de Postagem</h1>
<form asp-controller="Post" asp-action="EditaPost" method="post">
    @Html.EditorForModel()

    @if (!Model.Publicado)
    {
        <button asp-controller="Post" asp-action="PublicaPost" asp-route-id="@Model.ID">Publicar</button>
    }

    <button type="submit">Salvar</button>
    <button asp-controller="Post" asp-action="DeletarPost" asp-route-id="@Model.ID">Deletar Post</button>

    @*<input type="hidden" name="id" value="@Model.ID" />
        <label for="titulo">Título:<input name="titulo" required value="@Model.Titulo" /></label>
        @Html.ValidationMessage("titulo")
        <br />
        <label for="resumo">Resumo:<input type="text" name="resumo" required value="@Model.Resumo" /></label>
        @Html.ValidationMessage("resumo")
        <br />
        <label for="categoria">Categoria:<input name="categoria" value="@Model.Categoria" /></label>
        <br />*@

</form>

@section Scripts  {
    @*@Html.Partial("_Scripts"); // jeito obseleto*@
    <partial name="_Scripts"/>
}

CaleumBlog/Areas/Admin/Views/Shared/EditorTemplates/Post.cshtml
@model Post
@addTagHelper *, Microsot.AspNetCore.Mvc.TagHelpers

<input type="hidden" asp-for="ID" />
<input type="hidden" asp-for="Publicado" />
<input type="hidden" asp-for="DataPublicacao" />

<label asp-for="Titulo"></label>
<input asp-for="Titulo" />
<span asp-validation-for="Titulo"></span>
<br />
<label asp-for="Resumo"></label>
<textarea asp-for="Resumo" rows="5" cols="50"></textarea>
<span asp-validation-for="Resumo"></span>
<br />
<label asp-for="Categoria"></label>
<input asp-for="Categoria" />
<span asp-validation-for="Categoria"></span>
<br />

CaleumBlog/Areas/Admin/Views/Shared/MenuAdmin.cshtml
<aside>
    <h1>Administração</h1>
    <div>
        <ul>
            <li>
                <a asp-action="Index">Posts</a>
            </li>
        </ul>
    </div>
</aside>

CaleumBlog/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Administração - Resenha Cultural</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/estilo-admin.css" />
    <link rel="stylesheet" href="~/css/jquery-ui.css" />
</head>

<body>
    <partial name="MenuAdmin" />

    <main>
        @RenderBody()
    </main>

    @RenderSection(name:"Scripts", required:false)

</body>

</html>

CaleumBlog/Areas/Admin/Views/Shared/_Scripts.cshtml
<script src="~/js/jquery-1.10.2.js"></script>
<script src="~/js/jquery-ui.js"></script>
<script>
    // Fazendo o input Categoria ter autocomplete fornecido via JsonResult
    // pela Action do Controller
    $("input[name='Categoria']").autocomplete({
        source: function (request, response) {
            $.post("@Url.Action("CategoriaAutocomplete")",
                { termoDigitado: request.term },
                function (data) {
                    response(data);
                });
        }
    });
</script>

<!--<script src="~/js/jquery.validate.unobstrusive.js"></script>
<script src="~/js/jquery-1.10.2.js"></script>
<script>
    $("form").validate()
</script>
-->

CaleumBlog/Views/Home/Index.cshtml
@model IList<Post>

@if (Model.Count == 0)
{
    <article>
        <p>Ops! Não encontrei postagens com o termo "@ViewBag.TermoBuscado"</p>
    </article>
}
else if (ViewBag.TermoBuscado != null)
{
    <h3>Exibindo resultados para "@ViewBag.TermoBuscado"</h3>
}

@foreach (Post p in Model)
{
    <article>
        <h1>@p.Titulo</h1>
        <p>@p.Resumo</p>
    </article>
}

CaleumBlog/Views/Shared/_BarraLateral.cshtml
<aside>
    <div>
        <h3>Buscar</h3>
        <form asp-controller="Home" asp-action="Busca" method="get" class="inline">
            <div class="input-group">
                <input type="text" name="termo" class="form-control" placeholder="Buscar por..." />
                <span class="input-group-append">
                    <button class="btn btn-primary">Ok</button>
                </span>
            </div>
        </form>
    </div>

    <div id="categorias">
        <h3>Categorias</h3>
        <ul>
            @foreach (string categoria in ViewBag.Categorias)
            {
                <li><a asp-action="Categoria" asp-controller="Home" asp-route-id="@categoria">@categoria</a></li>
            }
        </ul>
    </div>

    <div id="autores">
        <h3>Autores</h3>
    </div>
</aside>

CaleumBlog/Views/Shared/_Cabecalho.cshtml
<header>
    <div class="jumbotron">
        <a asp-action="Index" asp-controller="Home"><h1>Resenha Cultural</h1></a>
        <p>Críticas bem humoradas sobre filmes, músicas, livros e tudo o que agita o cenário cultural.</p>
    </div>
</header>

CaleumBlog/Views/Shared/_LayoutPadrao.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Resenha Cultural</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/estilo.css" />
    <link rel="stylesheet" href="~/css/jquery-ui.css" />

</head>

<body>

    <partial name="_Cabecalho"/>

    <div class="container clearfix">
        <main>
            @RenderBody()
        </main>

        <partial name="_BarraLateral"/>
    </div>

    <partial name="_Rodape"/>
</body>

</html>

CaleumBlog/Views/Shared/_Rodape.cshtml
<footer>
    <p>&copy; Resenha Cultural - 2017</p>
</footer>

CaleumBlog/Views/Usuario/Login.cshtml
@model LoginViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Resenha Cultural - Login</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/estilo.css" />
</head>
<body>
    <div class="container">
        <main id="login-form">
            <h2>Resenha Cultural - Login</h2>
            @Html.ValidationSummary()
            @using (Html.BeginForm("Autentica", "Usuario", FormMethod.Post))
            {
                @Html.LabelFor(u => u.LoginName)
                @Html.TextBoxFor(u => u.LoginName, new { @class = "form-control" })

                @Html.LabelFor(u => u.Password)
                @Html.TextBoxFor(u => u.Password, new { @class = "form-control" })

                <input type="submit" value="Login" />
            }
        </main>

    </div>
</body>
</html>